### PR TITLE
Two commits (can be cherrypicked): Custom Env vars for Perl in settings, and convert tilda to home in paths

### PR DESCRIPTION
**Pull request by nugged**
**Feature 1:**

Add support for custom Perl environment variables

Introduced two new environment variables: perlEnv and perlEnvAdd.

- perlEnv: This is a hash to fully override the system's environment for PerlNavigator.
- perlEnvAdd: This is a hash to add or modify specific environment variables for PerlNavigator.

**Feature 2:**

Add support for expanding leading tildas in paths
+ if needed: variable to On/Off that.

### CODE REVIEW

**Comment by nugged** [comment]
NOTE: I tested this under MacOS (no Windows and I suspect it might be a different way of substituting Windows "home" or other relativeness).

**Comment by bscan** [comment]
This looks great, thanks for putting this together! I'll do some testing this weekend and merge it in. Some comments:

I don't think we'd need to disable the tilde expansion. Currently, tilde's simply don't work so having it on all the time is probably the best. Looks like they considered adding it in node, but decided against it: https://github.com/nodejs/node/issues/684 
And people seem to recommend untildify, which has 14 million weekly downloads and does the same thing ( os.homedir ) https://github.com/sindresorhus/untildify/blob/a901e25ef782d93df1eba04ed48f56c79d157c74/index.js#L10 
Although I greatly prefer your approach over bringing in a dependency for one line of code.

On Windows, the equivalent is probably `%USERPROFILE%` although far less used. We can probably just ignore it for now. I can test on Windows and Linux just to make sure nothing breaks, but I think it would be fine.

PerlEnv and PerlEnvAdd both make sense as well. I suspect Add is the more common case, where someone just needs to add or override a variable. Clearing out variables might have some unexpected effects, especially if someone's perl setup uses `PERL5LIB` or a `PERLCRITIC` profile. We can use the README to point people toward preferring `PerlEnvAdd` if needed. 

Thanks!

**Comment by nugged** [comment]
> PerlEnv and PerlEnvAdd both make sense as well. I suspect Add is the more common case, where someone just needs to add or override a variable. Clearing out variables might have some unexpected effects, especially if someone's perl setup uses PERL5LIB or a PERLCRITIC profile. We can use the README to point people toward preferring PerlEnvAdd if needed.

Good point. I reworked the idea of PerlEnv: two variables:
- perlEnv: Hash. Pass environment variables to the perl executable. Skipped if undefined.
- perlEnvAdd: Boolean. Add environment variables to the current environment, or totally replace (perlEnv related). The default is true.

More clean, and added by default, and perlEnvAdd can be used rarely.

**Comment by nugged** [comment]
Also: removed 

> Add expandLeadTildasInPaths Setting for Optional Tilda Expansion

commit at all, no need to on/off tildas' expansion.

**Comment by nugged** [comment]
... and removed Windows "placeholder" `~\\` which is actually not.

**Comment by bscan** [comment]
This is great, my apologies for the slow merge. Thanks again for putting this together!

**Pull request merged**
