### PR TITLE
* Add new option: perltidyEnabled, default is true (i.e. enabled). When

### PR DESCRIPTION
**Pull request by WhoIsSethDaniel**
set to false perltidy will not be run if requested

### CODE REVIEW

**Comment by WhoIsSethDaniel** [comment]
When set to false perhaps perlnavigator shouldn't advertise that it can do formatting. But I don't think I have the typescript skill to do that at this time. I mostly need this because of #11. Until I (or someone else) can fix that problem I need to suppress perlnavigator formatting.

**Comment by WhoIsSethDaniel** [comment]
If this gets accepted please consider publishing this so that it can be installed via npm.  Thanks. I believe the latest version availble via npm is 0.2.8. Thanks again.

**Comment by WhoIsSethDaniel** [comment]
any chance of review for this PR?

**Comment by bscan** [comment]
Looks good to me. Thanks for the contribution. I'll take a look and see if I can get it to stop advertising the ability as well. I'm also looking into Github actions this week as part of the hackathon, which would help keep npm, the vscode marketplace, open-vsix, and the binaries all in sync. Otherwise, I'll manually push all the changes after the conference. Thanks again for your help!

**Comment by WhoIsSethDaniel** [comment]
That's excellent news. Thank you @bscan

**Pull request merged**
