### PR TITLE
apply perlimports

### PR DESCRIPTION
**Pull request by oalders**
- Add perlimports.toml
- Apply perlimports

### CODE REVIEW

**Comment by oalders** [comment]
As I was poking around re: `perlimports`, I figured I'd run it on the repo to see what happens. 😄

**Comment by bscan** [comment]
Looks good to me. Cleanup is always welcome 😄 . Thanks for the commit.

**Comment by bscan** [comment]
Actually, the perlimports change to Filter::Simple in SourceStash.pm ends up breaking it. The error can be reproduced using the Filter::Simple example below. I didn't dig into too much because people generally shouldn't use Filter::Simple. I need it, but I believe my use case is a pretty rare one (source code introspection of code passed via stdin).  I reverted that particular change. 

Simplest example that fails.
``` perl
package BANG;
use Filter::Simple qw(FILTER); # This fails with an explicit import
 
FILTER {
    s/BANG\s+BANG/die 'BANG'/g;
};

1;
```

**Comment by oalders** [comment]
I'm sorry for breaking that! Looking at `Filter::Simple`, I think `perlimports` should just ignore it entirely. I'll make that change. Thanks for letting me know.

**Pull request merged**
